name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Build
        run: go build -o fuzzer ./cmd/fuzzer

      - name: Build Docker Image
        run: docker build -t network-protocol-fuzzer .

      - name: Run Docker Container
        run: docker run -d --name fuzzer network-protocol-fuzzer

      - name: Stop Docker Container
        run: docker stop fuzzer
